### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by n-smits** [LiamSwayne/Elratio#1]
i tried everything

**Comment by bllngr** [comment]
Have you tried turning it on and off again?

**Comment by LiamSwayne** [comment]
> i tried everything

did a double take when I saw this issue. Could you comment the full program on this issue? If I can't find the bug I'll have to call in the special ops debug team.

**Comment by LiamSwayne** [comment]
it's been ten hours and he hasn't replied. I think the special ops team got to him.

**Comment by yungifez** [comment]
Help ..........
