### ISSUE TITLE
Error message too concrete with clear instructions

### ISSUE THREAD

**Issue by jasoncarr0** [LiamSwayne/Elratio#2]
Hello! I saw this error message listed:

> \>\>\> Statements that do not end with a colon must end with a semicolon.

This makes it fairly clear what options are allowed and what to do, but as a person with experience in mathematics, I can't help but think that a more open-ended abstract definition might help:

> \>\>\> Statements must end with at least half a colon

This helps furthermore in potential scaling to trisemidemicolons once they're released.

**Comment by yungifez** [comment]
Sorry wtf
